---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker
  settings:
    dryrun: true
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    purge: true
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-amd64
    purge: true    
  when:
    exclude:
    - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: dryrun
  pull: always
  image: plugins/docker
  settings:
    dryrun: true
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    purge: true
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-arm64
  when:
    exclude:
    - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: dryrun
  pull: always
  image: plugins/docker
  settings:
    dryrun: true
    dockerfile: docker/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    purge: true
  when:
    event:
    - pull_request

- name: publish
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.linux.arm
    password:
      from_secret: docker_password
    repo: fouts/salt-master
    username:
      from_secret: docker_username
    auto_tag: true
    auto_tag_suffix: linux-arm
  when:
    exclude:
    - pull_request

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    spec: docker/manifest.tmpl
    autotag: true
  when:
    exclude:
    - pull_request
    - tags

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: dev
  when:
    status: [ success, failure ]

trigger:
  ref:
  - refs/heads/master
  - "refs/tags/**"
  - "refs/pull/**"

depends_on:
  - linux-arm
  - linux-amd64
  - linux-arm64

...
